name: banpay
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animated_react_button: 0.0.4
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  cached_network_image: 3.4.1
  cupertino_icons: ^1.0.8
  dio: 5.8.0+1

  flutter:
    sdk: flutter

  flutter_riverpod: 2.6.1

  # Storage
  hive: 2.2.3
  hive_flutter: 1.1.0

  logger: 2.5.0
  mockito: 5.4.4
  rxdart: 0.28.0
  riverpod: 2.6.1

dev_dependencies:
  build_runner: 2.4.13
  freezed: 2.4.6
  json_serializable: 6.7.1

  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0

  # Storage
  hive_generator: 2.0.1

flutter:
  uses-material-design: true
